version: '2'
services:
  php:
    image: yiisoftware/yii2-php:8.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    links:
      - mariaDB:db
  
  mariaDB:
    image: arm64v8/mariadb
    hostname: mariadb
    container_name: mariadb
    restart: always
    volumes:
      - ./docker/mariadb/data/:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_general_ci']

    ports:
      - 3307:3306
    environment:
      - TZ=Asia/Bangkok
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_USER=root
      - MYSQL_PASSWORD=docker
      - MYSQL_ROOT_HOST=% 

  phpmyadmin_mariadb:
    image: arm64v8/phpmyadmin
    restart: always
    links:
      - mariaDB:db
    ports:
      - 8200:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: docker
      PMA_HOST: mariaDB
  
  code-server:
    image: lscr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000 # Use the UID from the command mentioned above
      - PGID=100 # Use the GID from the command mentioned above
      - TZ=Asia/Kolkata # Time Zone of your choice for the container
      - PASSWORD=password # Login password for the Web UI
      - SUDO_PASSWORD=password # Sudo password (Optional)
    volumes:
      - ./vcode/config:/config # Volume mount for the container config files (Replace the path with the path on your host)
    ports:
      - 8443:8443 # Port mapping for the container in the format <host-port>:<container-port>. You can choose the <host-port> as per your convenience 
    restart: unless-stopped


