version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '81:80'
    links:
      - mariaDB-hr:db
  
  mariaDB-hr:
    image: mariadb
    hostname: mariadb-hr
    container_name: mariadb-hr
    restart: always
    volumes:
      - ./docker/mariadb/data/:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_general_ci']

    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Bangkok
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_USER=root
      - MYSQL_PASSWORD=docker
      - MYSQL_ROOT_HOST=% 

  phpmyadmin_mariadb:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mariaDB-hr:db
    ports:
      - 8200:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: docker
      PMA_HOST: mariaDB-hr
  


